version: 2
jobs:
  build:
    machine: true
    working_directory: ~/application
    steps:
      - checkout
      - run: source .env || true
      - run: docker-compose pull || true
      - run: docker-compose up -d --no-recreate
      - run: docker-compose exec -T php composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run: docker-compose exec -T php php artisan config:cache
      - run: docker-compose exec -T php php artisan key:generate
      - run: docker-compose exec -T php php artisan config:clear
      - run: docker-compose exec -T php phpunit --coverage-text --colors=never

      - deploy:
          name: Commit and push Docker images
          command: |
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            docker commit php ${DOCKER_REGISTRY}/php
            docker push ${DOCKER_REGISTRY}/php
            docker commit nginx ${DOCKER_REGISTRY}/nginx
            docker push ${DOCKER_REGISTRY}/nginx
