version: 2
jobs:
  build:
    machine: true
    working_directory: ~/application
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run: source .env || true
      - run: docker-compose pull || true
      - run: docker-compose up -d --no-recreate

  deploy:
    name: Commit and push Docker images
    command: |
      docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      docker commit php ${DOCKER_REGISTRY}/php
      docker push ${DOCKER_REGISTRY}/php
      docker commit nginx ${DOCKER_REGISTRY}/nginx
      docker push ${DOCKER_REGISTRY}/nginx

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
